baseURL = "https://baildon.co"
languageCode = "en-gb"
title = "Sean Baildon"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
pygmentsUseClasses = true
[author]
name = "Sean Baildon"
[markup]
[markup.highlight]
style = "solarized-light"
